### ISSUE TITLE
Bug: throw error when open setting modal

### ISSUE THREAD

**Issue by KeyonYan** [DeskIsle/DeskIsle#20]
An error is thrown when opening the settings modal.
`Uncaught Error: char indexing(index: -1)overflowed, allowed range:0 - 1
    at d.doMeasureText (content.js:1:637739)
    at measureText (content.js:1:637558)
    at Object.getSelectionRectForBasicInputV2 (content.js:1:641855)
    at Object.getSelectionRect (content.js:1:638983)
    at g (content.js:1:642751)
    at v (content.js:1:643765)
    at i (content.js:1:528788)
    at 692.js:2:87510`

**Comment by Shadowsight9** [comment]
can't reproduce
